### ISSUE TITLE
memory issue sample size above 60k

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#241] opened 2023-03-20 18:53 UTC
Error: Out of memory.  The --memory flag may be helpful.
Failed allocation size: 10917838720
[Mon Mar 20 14:45:22 2023]
Error in rule sample_level_ibd:
    jobid: 18
    output: sample_level/call_rate_2/samples_maf0.2_ld0.1.genome
    conda-env: /mnt/nfs/gigantor/ifs/DCEG/CGF/GWAS/AdhocProjects/FB32029_PanScanIV_Combined_QCandImputation/QC/GSAv1_EPIC-MALMO/no_freq_outlier_hg19/.snakemake/conda/1c75062d835d5565ddfbe54a1f55a9b8
    shell:
        sleep 10 && plink --bed sample_level/call_rate_2/samples_maf0.2_ld0.1_pruned.bed --bim sample_level/call_rate_2/samples_maf0.2_ld0.1_pruned.bim --fam sample_level/call_rate_2/samples_maf0.2_ld0.1_pruned.fam --genome full --min 0.05 --max 1.0 --threads 2 --memory 4096 --out sample_level/call_rate_2/samples_maf0.2_ld0.1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by 1teaspoon** [comment] 2023-10-26 20:24
current memory setting in sample_level_ibd and subject_level_ibd run out of memory when sample size is large (above 60k) when running on ccad2

**Comment by ngaddis** [comment] 2023-11-30 15:04
Calculate memory based on sample size

**Comment by jaamarks** [comment] 2024-01-23 21:49
It appears that the code is well-configured to handle memory issues, specifically within the module `GwasQcPipeline/src/cgr_gwas_qc/workflow/modules/plink.smk`.

<br><br>

At the beginning of the `plink.smk` file, there's a dictionary defined as follows:

```python
PLINK_BIG_MEM = {1: 1024 * 4, 2: 1024 * 64, 3: 1024 * 250}
```

This dictionary is utilized in various rules, including the `sample_level_ibd` rule (referred to as `genome` in `plink.smk`). In the `genome` rule, we can observe the use of this dictionary:

```python
resources:
   mem_mb=lambda wildcards, attempt: PLINK_BIG_MEM[attempt]
```

This sets `mem_mb` to 4,096 on attempt 1, and if that fails, it increases to 65,536 on attempt 2.

Working with a smaller 500-sample dataset, I performed some testing. Since this dataset doesn't encounter the memory issues of the larger +60K sample dataset, I adjusted the parameter as follows:

```python
PLINK_BIG_MEM = {1: 4 * 4, 2: 1024 * 64, 3: 1024 * 250}
```

After making this adjustment, I ran the sub-workflow `sample_qc`, and it behaved as expected. Attempt 1 failed because only 16mb were allocated, and the job was resubmitted with attempt 2. The resulting `plink` command looked like this:

```bash
plink --bed sample_level/call_rate_2/samples_maf0.2_ld0.1_pruned.bed --bim sample_level/call_rate_2/samples_maf0.2_ld0.1_pruned.bim --fam sample_level/call_rate_2/samples_maf0.2_ld0.1_pruned.fam --genome full --min 0.05 --max 1.0 --threads 4 --memory 65536 --out sample_level/call_rate_2/samples_maf0.2_ld0.1
```
* note `--memory 65536`

---

I'm considering conducting additional testing on larger datasets. If anyone has access to or can provide a dataset of approximately 60k samples, it would greatly assist resolving this issue.

**Comment by jaamarks** [comment] 2024-02-10 15:58
Currently working on getting the workflow to run for a 90K sample.
Having issues with `rule sample_concordance_plink:`
This was a local rule, but I am experimenting with making it a non-local rule.
It's tricky though because there are no logs, since this is a custom python script `../scripts/concordance_table.py`
This is a fairly simple script that reads the table from the previous IBD step ( `rules.sample_level_ibd.output[0].`), calculates additional columns related to identity-by-descent and concordance, applies threshold conditions to create boolean columns, and finally reindexes the DataFrame to include only specific columns.

Suggestion at last meeting was that we could increase the value of parameter `ibd_pi_hat_min` from 0.05 which would reduce the size of the .genome file from the IBD analysis. The `pi_hat_threshold` is currently set to 0.2, so we could practically increase `ibd_pi_hat_min` to this value.

It will help to first understand how much memory is needed to execute the script from the sample_concordance_plink rule because from looking at the Python script, it doesn't appear that it should take much time/resources. We will investigate more by running this as a standalone script and perform some troubleshooting techniques.

**Comment by jaamarks** [comment] 2024-02-11 03:16
This concordance_table.py script used in the sample_concordance_plink rule is using a ton of memory. The `sample_level/call_rate_2/samples_maf0.2_ld0.1.genome` IBD output file from the 90k sample is 18Gb. I tried to run the python concordance script as a stand-alone and it failed. Look how much memory it used before failing:

```
$ srun --job-name "marksja-concordance-test"  python concordance_table.py super_huge_18G_93046486Lines.genome 0.95 0.2  plink.csv

$  sacct -j 1072182 --format="JobID,JobName,AllocCPUS,MaxRSS,MaxVMSize,Elapsed" --units=G
       JobID    JobName  AllocCPUS     MaxRSS  MaxVMSize    Elapsed
------------ ---------- ---------- ---------- ---------- ----------
1072182      marksja-c+          1    183.62G    185.81G   05:17:40

```

I have a suspicion that the cause of this is an internal function that sorts the file. In particular, the concordance_table.py script is really simple and just calls:
```
def build(filename: Path, concordance_threshold: float, pi_hat_threshold: float) -> pd.DataFrame:

    return (
        plink.read_genome(filename)
        .assign(is_ge_pi_hat=lambda x: x.PI_HAT >= pi_hat_threshold)
        .assign(concordance=lambda x: x.IBS2 / (x.IBS0 + x.IBS1 + x.IBS2))
        .assign(is_ge_concordance=lambda x: x.concordance >= concordance_threshold)
        .reindex(DTYPES.keys(), axis=1)
    )

```

Let's take a look at plink.read_genome() from `GwasQcPipeline/src/cgr_gwas_qc/parsers/plink.py`, in particular, I am concerned with the code:
```
  def _sort_ids(x: pd.Series):
        """Sort IDs alphanumerically."""
        x["ID1"], x["ID2"] = sorted([x.IID1, x.IID2])
        return x
```

Need to think about how to make this more efficient, and if sorting is necessary.

**Comment by jaamarks** [comment] 2024-02-12 19:40
#### Dynamic Resources Allocation
Here is a snippet from the [Snakemake docs](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html) illustrating how to calculate the memory requirements based off of the size of the input file: 

```
rule:
    input:    ...
    output:   ...
    resources:
        mem_mb=lambda wc, input: max(2.5 * input.size_mb, 300)
    shell:
        "..."

```

**Comment by jaamarks** [comment] 2024-02-14 19:10
Increasing the value of parameter `ibd_pi_hat_min` in `software_params.py` from $`0.05`$ to $`0.2`$ makes a big difference on the file size of the output from the IBD step. For example, in the 90K sample, the line count of the output file from the IBD step was decreased by two orders of magnitudes from 93,046,486 lines (approximately 18.7 GB) to 289,627 lines.

Implementing this new approach significantly reduced resource usage when running the subsequent step foloowing the IBD analysis–the sample concordance step.
```
# sample concordance resource usage.
$ sacct -j $job --format="JobID,JobName,AllocCPUS,MaxRSS,MaxVMSize,Elapsed" --units=G

       JobID    JobName  AllocCPUS     MaxRSS  MaxVMSize    Elapsed
------------ ---------- ---------- ---------- ---------- ----------
1074195      sample_co+          1                         00:05:08
1074195.bat+      batch          1      1.36G      3.77G   00:05:08
```
* [MaxRSS](https://slurm.schedmd.com/sacct.html#OPT_MaxRSS)
* [MaxVMSize](https://slurm.schedmd.com/sacct.html#OPT_MaxVMSize)

**Closed as completed** 2024-04-01 13:45 UTC
Labels: bug
