### ISSUE TITLE
Ancestry = "Unknown" not shown in Table 3 Subject Counts by Ancestry Group

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#281] opened 2024-04-30 14:45 UTC

**Comment by 1teaspoon** [comment] 2024-05-01 19:41
ancestry assignment by graf-pop

**Comment by 1teaspoon** [comment] 2024-09-03 15:58
"Other" needs to be populated in sample_qc.csv so that subject_qc.csv have this ancestry info and the pca and hwe plots will be generated for this  ancestry group.

**Comment by carynwillis** [comment] 2024-10-16 01:45
Closing as a duplicate of issue #326 which has been completed and closed.

**Closed as completed by carynwillis** 2024-10-16 01:45 UTC
Labels: Priority1
